### ISSUE TITLE
在 ai_translator 之外调用 ai_translator 的子包会报错

### ISSUE THREAD

**Issue by Hughdw** [DjangoPeng/openai-quickstart#46]
报错信息：
![image](https://github.com/DjangoPeng/openai-quickstart/assets/1463783/04b7e0f9-17fe-4df2-82da-efc931d9956c)

调用 ai_translator 子包的文件（app.py）位置：
![image](https://github.com/DjangoPeng/openai-quickstart/assets/1463783/d823c27f-b2dc-4f78-9c04-19a2910202cb)

app.py 调用 ai_translator 子包的代码：
![image](https://github.com/DjangoPeng/openai-quickstart/assets/1463783/82dfc66f-418e-4bc4-a453-ad9b394b8a30)

**Comment by DjangoPeng** [comment]
应该是未正确将 openai-translator 设置为 IDE 的项目路径。

请查看 PyCharm 相关手册，我这里先关闭此 issue 了
