### ISSUE TITLE
Add latest course(08/13) into schedule

### ISSUE THREAD

**Issue by DjangoPeng** [DjangoPeng/openai-quickstart#48]
We updated the file directory of LangChain code demo on latest course(08.13)

@richzw Could you please sync the schedule and filepath?

**Comment by DjangoPeng** [comment]
A layout issue should be fixed as below:

![image](https://github.com/DjangoPeng/openai-quickstart/assets/16943353/ae241f59-d1ae-4739-9001-df680ddb8229)

**Comment by richzw** [comment]
I will fix it right now.

**Comment by DjangoPeng** [comment]
课程表已全部完成更新，关闭 issue
